### ISSUE TITLE
[FEATURE] Passport Upgrade Flow

### ISSUE THREAD

**Issue by alexjball** [codeforboston/police-data-trust#162]
Public users can request to upgrade their account to a passport account, which grants them access to more data. Admin users review and approve or deny the upgrade. 

## API Definition

We will add `/api/v1/passport` routes to flask that the frontend uses to drive the upgrade flow. Additionally, we will include the `role` field in the `/api/v1/auth/test` response, so the frontend knows the level of access of the current user.

- `/requestUpgrade`: `POST` with form responses to the `/passport` page. Fails if too many attempts or pending request
- `/listRequests`: `GET` only accessible by admins. request `{ id: string, decision: "pending" | "approved" | "denied", user, details }`
- `/completeRequest`: `PUT` only accessible by admins, body `{ requestId: string, decision: string }`
- `/getRequestStatus`: `GET` for the current status of the user's latest request, body `{ status: "none" | "pending" | "approved" | "denied" }`
- `/revokeAccess`: `PUT` revert the passport user's account to public

## Backend Implementation

- [ ] Create a table to store the upgrade requests
- [ ] Enforce role-based authorization
- [ ] Update `User.role` on approval
- [ ] Include `User.role` in `/api/v1/auth/test` response
- [ ] Add handlers and tests for new routes

## Frontend Implementation

- [ ] Add request handlers and tests for new routes
- [ ] Add mock api handlers
- [ ] Submit form responses and display submission status
- [ ] Add pending request state to `/passport` form
- [ ] Display profile type, including pending request state
- [ ] Handle reverting to a public account
- [ ] Add tests for upgrade flow
- [ ] Add admin-only page for completing upgrade requests

**Comment by ryanmahan** [comment]
I can take on the API half right now! Still open for a UI dev

**Comment by alexjball** [comment]
@arutfield is working on adding the user role  to the /test endpoint

**Comment by ryanmahan** [comment]
can I suggest some different route names?
`POST /passportRequests` to create a passport request
`GET /passportRequests` with support for a few different query params: `status`, `userId` for a simple search of passport requests
`PUT /passportRequests/:passportRequestId/status` with a body of `status`, if accepted, promotes the user to the requested role. Could also replace this with a patch endpoint and implement something like a merge.
`GET /passportRequests/:passportRequestId` returns a single passport request
`PUT /user/:userId/role` with a body of their new role (for demotion/promotion)

Pros of sticking to http verb endpoints with noun routes. Retaining the same functionality as the proposed endpoints

**Comment by ryanmahan** [comment]
Have progress towards this stored over on https://github.com/ryanmahan/police-data-trust/tree/passport-requests. Closing this issue until we need this functionality or something like it in the future.
