### ISSUE TITLE
[FEATURE] Password Recovery Flow

### ISSUE THREAD

**Issue by alexjball** [codeforboston/police-data-trust#165]
[Figma](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC--2?node-id=1575%3A195)

`/v1/api/auth` routes:
- `/resetPassword`: `POST` with body `{email: string, phoneNumber: string }`. Support email before phone numbers. For security, returns 200 regardless of existing account.

**Note**: `flask_user`, the library we use to manage users, automatically installs routes related to password recovery and email verification. Rather than implement our own routes, we could leverage these. These are the `/user` routes listed by `flask routes`

# Frontend Work
- [ ] Build forgot password form
- [ ] Connect form to `/resetPassword` endpoint
- [ ] Test password recovery flow

# Backend Work
- [ ] Use [`flask_user`](https://flask-user.readthedocs.io/en/latest/introduction.html) to send and handle recovery emails
- [ ] Configure credentials for sending emails
- [x] Create `/resetPassword` route

**Comment by ryanmahan** [comment]
Looks like a lot of the `/user` routes provided by `flask-user` are all packaged with the views provided. Looking into seeing if we can change the email URL to direct to the frontend and use as much of the flask user routes as possible.
