### ISSUE TITLE
Basic Incident Search API

### ISSUE THREAD

**Issue by alexjball** [codeforboston/police-data-trust#191]
We will implement routes and queries to support basic incident search, following the flow described in [figma](https://www.figma.com/file/TM86P6ePUar5g24pk4h6Du/NPDC--2?node-id=193%3A11). The focus of this work is to support the initial implementation of the frontend search flow and to set up patterns for other search flows on the backend, not to build a comprehensive API.

# API Routes

We will add search routes under `/api/v1/search`, in a new `routes/search.py` file. All routes require authentication as a public or higher-access user.

- `GET /incidents`: body `{location: string, startDate: string, endDate:string, incidentType: string}` returns a list of incidents matching the search criteria. Large result sets are paginated. Incidents contain data according to the backend incident data model.

# Backend

- [ ] If needed, update the backend incident model to support the frontend search flow.
- [ ] Define routes
- [ ] Add development seeds with fake incidents
- [ ] Implement routes using SQLAlchemy queries
- [ ] Test routes

# Frontend

- [ ] Add routes to `api.ts`
- [ ] Implement mock handlers for routes using fake incidents
- [ ] Update `api.test.ts` and run e2e and mock integration tests
- [ ] Add "engineer" UI that exercises search interactions. Just text fields -> api call -> text results
